import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";
import { dirname } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 复制样式文件到输出目录
function copyStyles() {
  const source = "styles.css";
  const dest = "styles.css";
  
  if (existsSync(source)) {
    copyFileSync(source, dest);
    console.log(`✅ Copied ${source} to ${dest}`);
  } else {
    console.warn(`⚠️  Source file not found: ${source}`);
  }
}

// 确保输出目录存在
function ensureOutputDir() {
  const dir = dirname("main.js");
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

// 构建配置
const buildConfig = {
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  plugins: [
    {
      name: "copy-styles",
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length === 0) {
            copyStyles();
          }
        });
      }
    }
  ]
};

// 开发模式
if (!prod) {
  console.log("🚀 Starting development build...");
  ensureOutputDir();
  
  const context = await esbuild.context(buildConfig);
  await context.watch();
  
  console.log("👀 Watching for changes...");
  console.log("📁 Output files:");
  console.log("   - main.js");
  console.log("   - styles.css");
  console.log("   - manifest.json");
} 
// 生产模式
else {
  console.log("🏗️  Starting production build...");
  ensureOutputDir();
  
  try {
    await esbuild.build(buildConfig);
    console.log("✅ Build completed successfully!");
    console.log("📦 Output files:");
    console.log("   - main.js (minified)");
    console.log("   - styles.css");
    console.log("   - manifest.json");
    console.log("   - versions.json");
  } catch (error) {
    console.error("❌ Build failed:", error);
    process.exit(1);
  }
  
  process.exit(0);
}